print('Elrepülnek a napok, hetek, hónapok. ') 
print('Néha furcsa látni, most már hol vagyok. ')
print('Elértem azt mind, amiben nem hittem. ') 
print('És a barátaim mind magammal vittem. ')
nev = input('Hogy hívnak? ')
szuletesnap = input('Mikor születtél? ')
szuleteshely = input('Hol születtél? ')
lakcim = input('Hol laksz? ')
x = int(input('Adjon meg egy számot! '))
y = int(input('Adjon meg egy másik számot! '))
print(x,y)
print(y,x)
a = int(input('Adjon meg egy számot! '))
b= int(input('Adjon meg egy másik számot! '))
print('A téglalap területe',a*b)
print('A téglalap kerülete',2*(a+b))
a = int(input('Adjon meg egy számot! '))
b = int(input('Adjon meg egy másik számot! '))
c = int(input('Adjon meg egy harmadik számot! '))
print('A háromszög területe',a*b/2)
print('A háromszög kerülete',a+b+c)

